import { pool } from "../db";

export const getTODO = async () => {
  try {
    const query = `
      SELECT
	P.NOMBRE AS NOMBRE_PROYECTO,

	TEM.NOMBRE AS TEMATICA,
	ES.TIPO AS ESTATUS,

	
	TA.TIPO as Tipo_apoyo,
	AP.DETALLE AS DETALLE_APOYO,
	P.MONTO,
	
	AC.NOMBRE as academico,
	UA.NOMBRE as unidad_academica,
	CONV.NOMBRE AS CON_NOMBRE,
	TC.NOMBRE as tipo_convocatoria,
	IC.NOMBRE as  institucion_convocatoria,
	P.FECHA_POSTULACION,
	P.COMENTARIOS
FROM
	PROYECTO AS P
	JOIN APOYO AS AP ON AP.ID_APOYO = P.ID_APOYO
	JOIN TIPO_APOYO AS TA ON TA.ID_TIPO_APOYO = P.ID_APOYO
	JOIN ESTATUS AS ES ON ES.ID_ESTATUS = P.ID_ESTATUS
	JOIN TEMATICA AS TEM ON TEM.ID_TEMATICA = P.ID_TEMATICA
	JOIN PROYECTOACADEMICO AS AYP ON AYP.ID_PROYECTO = P.ID_PROYECTO
	JOIN ACADEMICO AS AC ON AC.ID_ACADEMICO = AYP.ID_ACADEMICO
	JOIN UNIDADACADEMICA AS UA ON P.UNIDAD = UA.ID_UNIDAD
	JOIN CONVOCATORIA AS CONV ON P.ID_CONVOCATORIA = CONV.ID_CONVOCATORIA
	JOIN TIPO_CONVO AS TC ON TC.ID = CONV.TIPO
	JOIN INST_CONVO AS IC ON IC.ID = CONV.INSTITUCION
    `;
    
    const result = await pool.query(query);
    return result.rows;
  } catch (error) {
    console.error("Error en getTODO:", error);
    throw error;
  }
};